#!/usr/bin/env python3
"""Static site generator for mmlaw.ge.

    python3 tools/build.py          build all pages into the repo root
    python3 tools/build.py --og     also render social share images (needs Google Chrome)

Text lives in tools/content.py; styles in assets/site.css; behaviour in assets/site.js.
"""
import hashlib
import html
import json
import os
import shutil
import subprocess
import sys
import tempfile

sys.path.insert(0, os.path.dirname(__file__))
from content import (SITE, LANGS, DEFAULT_LANG, LOCALES, LANG_LABEL, LANG_NAME, T, PAGES,
                     HOME_FAQ, SERVICES, ABOUT, PRIVACY, POSTS, SLUGS,
                     FOREIGN_UI, FOREIGN_HUB, FOREIGN_TOPICS)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
D = SITE["domain"]
GENERATED_MARK = "<!-- generated by tools/build.py -->"
FORM_ENDPOINT = "https://formsubmit.co/ajax/" + SITE["email"]
def _asset_version():
    """Changes whenever site.css or site.js change, so browsers never use a stale copy."""
    h = hashlib.sha1()
    for name in ("site.css", "site.js"):
        with open(os.path.join(ROOT, "assets", name), "rb") as f:
            h.update(f.read())
    return h.hexdigest()[:10]


ASSET_V = _asset_version()

e = html.escape


# ------------------------------------------------------------------ helpers
def localize(lang, key):
    """Page key ('services/criminal-defense/') -> address words in that language."""
    parts = [x for x in key.split("/") if x]
    if not parts:
        return ""
    out = [SLUGS["sections"][parts[0]][lang]]
    if len(parts) > 1:
        group = {"services": "services", "blog": "posts", "foreigners": "foreigners"}[parts[0]]
        out.append(SLUGS[group].get(parts[1], {}).get(lang, parts[1]))
    return "/".join(out) + "/"


def url(lang, path=""):
    """Site-relative URL for a page key ('' = home, 'about/', 'services/<slug>/' ...)."""
    if lang == DEFAULT_LANG and not path:
        return "/"  # Georgian home lives on the bare domain
    return f"/{lang}/" + localize(lang, path)


def abs_url(lang, path=""):
    return D + url(lang, path)


def with_brand(title):
    """Append the brand only when the title still fits in a search result."""
    return f"{title} | MMLAW" if len(title) <= 52 else title


def svc(slug):
    return next(s for s in SERVICES if s["slug"] == slug)


def fmt_date(iso, lang):
    y, m, d = (int(x) for x in iso.split("-"))
    months = {
        "ka": ["იანვარი", "თებერვალი", "მარტი", "აპრილი", "მაისი", "ივნისი", "ივლისი", "აგვისტო", "სექტემბერი", "ოქტომბერი", "ნოემბერი", "დეკემბერი"],
        "en": ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
        "ru": ["января", "февраля", "марта", "апреля", "мая", "июня", "июля", "августа", "сентября", "октября", "ноября", "декабря"],
    }[lang]
    if lang == "en":
        return f"{months[m - 1]} {d}, {y}"
    return f"{d} {months[m - 1]}, {y}" if lang == "ka" else f"{d} {months[m - 1]} {y} г."


ICONS = {
    "scale": '<path d="m16 16 3-8 3 8c-.87.65-1.92 1-3 1s-2.13-.35-3-1Z"/><path d="m2 16 3-8 3 8c-.87.65-1.92 1-3 1s-2.13-.35-3-1Z"/><path d="M7 21h10"/><path d="M12 3v18"/><path d="M3 7h2c2 0 5-1 7-2 2 1 5 2 7 2h2"/>',
    "pin": '<path d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z"/><circle cx="12" cy="10" r="3"/>',
    "clock": '<circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/>',
    "phone": '<path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"/>',
    "mail": '<rect width="20" height="16" x="2" y="4" rx="2"/><path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7"/>',
    "arrow": '<path d="M5 12h14"/><path d="m12 5 7 7-7 7"/>',
    "back": '<path d="M19 12H5"/><path d="m12 19-7-7 7-7"/>',
    "check": '<path d="M20 6 9 17l-5-5"/>',
    "lock": '<rect width="18" height="11" x="3" y="11" rx="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/>',
    "menu": '<path d="M4 6h16"/><path d="M4 12h16"/><path d="M4 18h16"/>',
    "chev": '<path d="m6 9 6 6 6-6"/>',
    "alert": '<path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3"/><path d="M12 9v4"/><path d="M12 17h.01"/>',
    "chat": '<path d="M7.9 20A9 9 0 1 0 4 16.1L2 22Z"/>',
    "shield": '<path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"/>',
    "gavel": '<path d="m14.5 12.5-8 8a2.119 2.119 0 1 1-3-3l8-8"/><path d="m16 16 6-6"/><path d="m8 8 6-6"/><path d="m9 7 8 8"/><path d="m21 11-8-8"/>',
    "landmark": '<line x1="3" x2="21" y1="22" y2="22"/><line x1="6" x2="6" y1="18" y2="11"/><line x1="10" x2="10" y1="18" y2="11"/><line x1="14" x2="14" y1="18" y2="11"/><line x1="18" x2="18" y1="18" y2="11"/><polygon points="12 2 20 7 4 7"/>',
    "child": '<circle cx="12" cy="8" r="5"/><path d="M20 21a8 8 0 0 0-16 0"/>',
    "briefcase": '<path d="M16 20V4a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16"/><rect width="20" height="14" x="2" y="6" rx="2"/>',
    "building": '<path d="M6 22V4a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v18Z"/><path d="M6 12H4a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2h2"/><path d="M18 9h2a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2h-2"/><path d="M10 6h4"/><path d="M10 10h4"/><path d="M10 14h4"/><path d="M10 18h4"/>',
    "home": '<path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><polyline points="9 22 9 12 15 12 15 22"/>',
    "users": '<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/>',
    "bulb": '<path d="M15 14c.2-1 .7-1.7 1.5-2.5 1-.9 1.5-2.2 1.5-3.5A6 6 0 0 0 6 8c0 1 .2 2.2 1.5 3.5.7.7 1.3 1.5 1.5 2.5"/><path d="M9 18h6"/><path d="M10 22h4"/>',
    "x": '<path d="M18 6 6 18"/><path d="m6 6 12 12"/>',
    "idcard": '<rect width="20" height="14" x="2" y="5" rx="2"/><circle cx="8" cy="12" r="2"/><path d="M14 10h4"/><path d="M14 14h4"/><path d="M5 17c.6-1.2 1.7-1.8 3-1.8s2.4.6 3 1.8"/>',
    "globe": '<circle cx="12" cy="12" r="10"/><path d="M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20"/><path d="M2 12h20"/>',
    "sun": '<circle cx="12" cy="12" r="4"/><path d="M12 2v2"/><path d="M12 20v2"/><path d="m4.93 4.93 1.41 1.41"/><path d="m17.66 17.66 1.41 1.41"/><path d="M2 12h2"/><path d="M20 12h2"/><path d="m6.34 17.66-1.41 1.41"/><path d="m19.07 4.93-1.41 1.41"/>',
    "moon": '<path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z"/>',
    "callback": '<path d="M14.05 2a9 9 0 0 1 8 7.94"/><path d="M14.05 6A5 5 0 0 1 18 10"/><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"/>',
    "fb": '<path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"/>',
    "in": '<path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z"/><rect width="4" height="12" x="2" y="9"/><circle cx="4" cy="4" r="2"/>',
}


def icon(name, size=16, sw=2, cls=""):
    c = f' class="{cls}"' if cls else ""
    return (f'<svg{c} width="{size}" height="{size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" '
            f'stroke-width="{sw}" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">{ICONS[name]}</svg>')


# ------------------------------------------------------------------ JSON-LD
def firm_ld(lang):
    t = T[lang]
    return {
        "@type": "LegalService",
        "@id": D + "/#firm",
        "name": SITE["legal_name"],
        "alternateName": ["MMLAW", "MM Law", "mmlaw.ge", "MMLAW საადვოკატო ბიურო", "Юридическая фирма MMLAW"],
        "description": PAGES["home"][lang][1],
        "url": D + "/",
        "logo": {"@type": "ImageObject", "url": D + "/icon-512.png", "width": 512, "height": 512},
        "image": D + f"/assets/og-{lang}.png",
        "telephone": SITE["phone"],
        "email": SITE["email"],
        "address": {"@type": "PostalAddress", "addressLocality": "Tbilisi", "addressCountry": "GE"},
        "areaServed": [{"@type": "City", "name": "Tbilisi"}, {"@type": "Country", "name": "Georgia"}],
        "knowsAbout": [s[lang]["name"] for s in SERVICES],
        "makesOffer": {"@type": "Offer", "name": t["s4"], "price": "0", "priceCurrency": "GEL",
                       "description": t["badge_text"]},
        "knowsLanguage": ["ka", "en", "ru"],
        "openingHoursSpecification": [{
            "@type": "OpeningHoursSpecification",
            "dayOfWeek": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
            "opens": "10:00", "closes": "18:00",
        }],
        "contactPoint": [{
            "@type": "ContactPoint", "telephone": SITE["phone"], "email": SITE["email"],
            "contactType": "customer service", "availableLanguage": ["Georgian", "English", "Russian"],
        }],
        "sameAs": [SITE["facebook"], SITE["linkedin"], "https://" + SITE["former_domain"]],
        "slogan": t["footer_tag"],
        "hasOfferCatalog": {
            "@type": "OfferCatalog", "name": t["svc_eyebrow"],
            "itemListElement": [{
                "@type": "Offer",
                "itemOffered": {"@type": "Service", "name": s[lang]["name"], "url": abs_url(lang, f"services/{s['slug']}/")},
            } for s in SERVICES],
        },
    }


def website_ld():
    return {
        "@type": "WebSite", "@id": D + "/#website", "url": D + "/", "name": "MMLAW",
        "alternateName": ["MMLAW Law Firm", "mmlaw.ge", "MMLAW საადვოკატო ბიურო"],
        "inLanguage": LANGS, "publisher": {"@id": D + "/#firm"},
    }


def crumbs_ld(lang, trail):
    return {
        "@type": "BreadcrumbList", "@id": abs_url(lang, trail[-1][1]) + "#breadcrumb",
        "itemListElement": [
            {"@type": "ListItem", "position": i + 1, "name": name, "item": abs_url(lang, p)}
            for i, (name, p) in enumerate(trail)
        ],
    }


def faq_ld(lang, path, faqs):
    return {
        "@type": "FAQPage", "@id": abs_url(lang, path) + "#faq", "inLanguage": lang,
        "mainEntity": [{"@type": "Question", "name": q, "acceptedAnswer": {"@type": "Answer", "text": a}} for q, a in faqs],
    }


def webpage_ld(lang, path, title, desc, kind="WebPage", trail=None):
    d = {
        "@type": kind, "@id": abs_url(lang, path) + "#webpage", "url": abs_url(lang, path),
        "name": title, "description": desc, "inLanguage": lang,
        "isPartOf": {"@id": D + "/#website"}, "about": {"@id": D + "/#firm"},
        "primaryImageOfPage": {"@type": "ImageObject", "url": D + f"/assets/og-{lang}.png"},
        "dateModified": SITE["updated"],
    }
    if trail:
        d["breadcrumb"] = {"@id": abs_url(lang, trail[-1][1]) + "#breadcrumb"}
    return d


# ------------------------------------------------------------------ layout
# Live addresses that were later renamed -> (lang, page key)
LEGACY = {"/ka/momsakhureba/siskhlis-samartali/": ("ka", "services/criminal-defense/"),
          "/ru/uslugi/ugolovnaya-zashchita/": ("ru", "services/criminal-defense/"),
          "/ka/chvens-shesakheb/": ("ka", "about/")}

IMAGE_SIZES = {"/assets/blog/judge.jpg": (900, 900)}


def head(lang, path, title, desc, og_type="website", image=None, ld=(), noindex=False, extra=""):
    image = image or f"/assets/og-{lang}.png"
    iw, ih = IMAGE_SIZES.get(image, (1200, 630))
    fonts = ("""<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Noto+Sans+Georgian:wght@400;500;600;700&display=swap">
""" if lang == "ka" else "")
    alts = "".join(f'<link rel="alternate" hreflang="{l}" href="{abs_url(l, path)}">' for l in LANGS)
    alts += f'<link rel="alternate" hreflang="x-default" href="{abs_url(DEFAULT_LANG, path)}">'
    og_alt = "".join(f'<meta property="og:locale:alternate" content="{LOCALES[l]}">' for l in LANGS if l != lang)
    graph = json.dumps({"@context": "https://schema.org", "@graph": list(ld)}, ensure_ascii=False, separators=(",", ":"))
    robots = "noindex, follow" if noindex else "index, follow, max-image-preview:large, max-snippet:-1"
    return f"""<!doctype html>
<html lang="{lang}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{e(title)}</title>
<meta name="description" content="{e(desc)}">
<meta name="robots" content="{robots}">
<link rel="canonical" href="{abs_url(lang, path)}">
{alts}
<meta property="og:type" content="{og_type}">
<meta property="og:site_name" content="MMLAW — mmlaw.ge">
<meta property="og:title" content="{e(title)}">
<meta property="og:description" content="{e(desc)}">
<meta property="og:url" content="{abs_url(lang, path)}">
<meta property="og:image" content="{D}{image}">
<meta property="og:image:width" content="{iw}">
<meta property="og:image:height" content="{ih}">
<meta property="og:image:alt" content="{e(title)}">
<meta property="og:locale" content="{LOCALES[lang]}">
{og_alt}
<meta name="twitter:card" content="summary_large_image">
<meta name="author" content="MMLAW">{extra}
<meta name="color-scheme" content="light dark">
<meta name="theme-color" content="#ffffff" media="(prefers-color-scheme: light)">
<meta name="theme-color" content="#09090b" media="(prefers-color-scheme: dark)">
<script>try{{var m=localStorage.getItem("theme");if(m==="light"||m==="dark")document.documentElement.setAttribute("data-theme",m)}}catch(e){{}}</script>
<link rel="icon" href="/favicon.ico" sizes="any">
<link rel="icon" href="/favicon.svg" type="image/svg+xml">
<link rel="apple-touch-icon" href="/apple-touch-icon.png">
<link rel="manifest" href="/site.webmanifest">
{fonts}<link rel="stylesheet" href="/assets/site.css?v={ASSET_V}">
<script type="application/ld+json">{graph}</script>
</head>"""


def lang_switch(lang, path):
    out = []
    for l in LANGS:
        cur = ' aria-current="true"' if l == lang else ""
        out.append(f'<a href="{url(l, path)}" hreflang="{l}" lang="{l}" title="{LANG_NAME[l]}"{cur}>{LANG_LABEL[l]}</a>')
    return f'<nav class="lang" aria-label="Language">{"".join(out)}</nav>'


def nav_links(lang, active):
    t = T[lang]
    items = [("home", "", t["nav_home"]), ("about", "about/", t["nav_about"]), ("services", "services/", t["nav_services"]),
             ("foreigners", "foreigners/", FOREIGN_UI[lang]["nav"]), ("blog", "blog/", t["nav_blog"]), ("contact", "contact/", t["nav_contact"])]
    return "".join(
        f'<a href="{url(lang, p)}"{" aria-current=\"page\"" if k == active else ""}>{e(n)}</a>' for k, p, n in items)


def brand(lang, small=False):
    s = 32 if small else 36
    return (f'<span class="logo-mark" style="width:{s}px;height:{s}px">{icon("scale", 18 if small else 20, 1.75)}</span>'
            f'<span class="brand-txt"><span class="brand-name">MMLAW</span>'
            f'{"" if small else f"<span class=brand-sub>{e(T[lang]["law_firm"])}</span>"}</span>')


def theme_btn(lang, cls):
    t = T[lang]
    return (f'<button class="{cls}" type="button" data-theme-toggle aria-label="{e(t["theme"])}" title="{e(t["theme"])}">'
            f'{icon("moon", 16, cls="i-moon")}{icon("sun", 16, cls="i-sun")}</button>')


def header(lang, path, active):
    t = T[lang]
    return f"""<a class="skip" href="#main">{e(t["skip"])}</a>
<div class="topbar"><div class="wrap topbar-in">
<div class="topbar-info"><a class="tb-phone" href="tel:{SITE["phone"]}">{icon("phone", 14)}{SITE["phone_display"]}</a><span>{icon("pin", 14)}{e(t["city"])}</span><span class="hide-sm">{icon("clock", 14)}{e(t["hours"])}</span></div>
<div class="tb-right">{lang_switch(lang, path)}{theme_btn(lang, "theme-btn theme-sm")}</div>
</div></div>
<header class="hdr"><div class="wrap hdr-in">
<a class="brand" href="{url(lang)}" aria-label="MMLAW — {e(t["nav_home"])}">{brand(lang)}</a>
<nav class="nav" aria-label="Main">{nav_links(lang, active)}</nav>
<div class="hdr-actions">
<a class="btn btn-outline mono hdr-phone" href="tel:{SITE["phone"]}">{icon("phone")}{SITE["phone_display"]}</a>
<a class="btn btn-primary hdr-cta" href="{url(lang, "contact/")}">{e(t["cta"])}</a>
<div class="hdr-lang">{lang_switch(lang, path)}</div>
{theme_btn(lang, "theme-btn theme-hdr")}
<button class="menu-btn" type="button" aria-expanded="false" aria-controls="mnav" aria-label="{e(t["menu"])}">{icon("menu", 20, cls="i-open")}{icon("x", 20, cls="i-close")}</button>
</div>
</div>
</header>
<div class="mnav" id="mnav" hidden><div class="wrap mnav-in">
<nav class="mnav-main" aria-label="Mobile">{nav_links(lang, active)}</nav>
<div class="mnav-sec"><span class="mnav-h">{e(t["svc_eyebrow"])}</span>
<div class="mnav-svc">{"".join(f'<a href="{url(lang, "services/" + s["slug"] + "/")}">{icon(s["icon"], 16, 1.75)}{e(s[lang]["name"])}</a>' for s in SERVICES)}</div></div>
<div class="mnav-btns">
<a class="btn btn-primary btn-block" href="tel:{SITE["phone"]}">{icon("phone")}{SITE["phone_display"]}</a>
<a class="btn btn-outline btn-block" href="{SITE["whatsapp"]}" rel="noopener" target="_blank">{icon("chat")}WhatsApp</a>
</div>
<div class="mnav-lang">{lang_switch(lang, path)}</div>
<p class="mnav-info">{icon("pin", 14)}{e(t["city"])} · {e(t["hours"])}</p>
</div></div>"""


def mobile_bar(lang):
    t = T[lang]
    return f"""<nav class="mbar" aria-label="{e(t["f_contact"])}">
<a href="tel:{SITE["phone"]}">{icon("phone", 20, 1.75)}<span>{e(t["m_call"])}</span></a>
<a href="{SITE["whatsapp"]}" rel="noopener" target="_blank">{icon("chat", 20, 1.75)}<span>WhatsApp</span></a>
<a class="mbar-cta" href="{url(lang, "contact/")}" data-consult-link>{icon("mail", 20, 1.75)}<span>{e(t["m_cta"])}</span></a>
</nav>"""


def footer(lang):
    t = T[lang]
    firm = [(t["nav_about"], "about/"), (t["nav_services"], "services/"), (FOREIGN_UI[lang]["nav"], "foreigners/"),
            (t["nav_blog"], "blog/"), (t["nav_contact"], "contact/")]
    prac = SERVICES[:5]
    return f"""<footer class="ftr"><div class="wrap ftr-in">
<div class="ftr-top">
<div class="ftr-brand">
<a class="brand" href="{url(lang)}">{brand(lang, small=True)}</a>
<p>{e(t["footer_tag"])}</p>
<div class="socials" aria-label="{e(t["socials"])}">
<a href="{SITE["facebook"]}" rel="noopener" target="_blank" aria-label="Facebook">{icon("fb", 16)}</a>
<a href="{SITE["linkedin"]}" rel="noopener" target="_blank" aria-label="LinkedIn">{icon("in", 16)}</a>
<a href="{SITE["whatsapp"]}" rel="noopener" target="_blank" aria-label="WhatsApp">{icon("chat", 16)}</a>
</div>
</div>
<div class="ftr-cols">
<div><span class="ftr-h">{e(t["f_firm"])}</span>{"".join(f'<a href="{url(lang, p)}">{e(n)}</a>' for n, p in firm)}</div>
<div><span class="ftr-h">{e(t["f_practice"])}</span>{"".join(f'<a href="{url(lang, "services/" + s["slug"] + "/")}">{e(s[lang]["name"])}</a>' for s in prac)}</div>
<div><span class="ftr-h">{e(t["f_contact"])}</span>
<a href="tel:{SITE["phone"]}" class="mono">{SITE["phone_display"]}</a>
<a href="mailto:{SITE["email"]}">{SITE["email"]}</a>
<span>{e(t["city"])}</span><span>{e(t["hours"])}</span></div>
</div>
</div>
<p class="ftr-disc">{e(t["disclaimer"])}</p>
<div class="ftr-bottom"><span>© 2026 MMLAW · mmlaw.ge. {e(t["rights"])}</span><a href="{url(lang, "privacy/")}">{e(t["privacy"])}</a></div>
</div></footer>
<script src="/assets/site.js?v={ASSET_V}" defer></script>"""


def page(lang, path, title, desc, main, active=None, ld=(), og_type="website", image=None, noindex=False, extra=""):
    return (head(lang, path, title, desc, og_type, image, ld, noindex, extra) + "\n<body>\n" + header(lang, path, active)
            + f'\n<main id="main">\n{main}\n</main>\n' + footer(lang) + mobile_bar(lang) + call_sheet(lang) + "\n</body>\n</html>\n" + GENERATED_MARK + "\n")


# ------------------------------------------------------------------ components
HONEYPOT = '<input class="hp" type="text" name="_honey" tabindex="-1" autocomplete="off" aria-hidden="true">'


def form_attrs(lang, subject):
    t = T[lang]
    return (f'action="{FORM_ENDPOINT}" method="post" data-email="{SITE["email"]}" data-wa="{SITE["whatsapp"]}" '
            f'data-subject="{e(subject)}" data-sending="{e(t["sending"])}" data-ok="{e(t["sent_ok"])}" data-err="{e(t["sent_err"])}"')


def call_sheet(lang):
    t = T[lang]
    return f"""<dialog class="sheet" id="call-sheet" aria-labelledby="sh-t">
<div class="sh-in">
<div class="sh-head"><div><h2 id="sh-t" tabindex="-1" autofocus>{e(t["sh_title"])}</h2><p>{e(t["sh_sub"])}</p></div>
<button class="sh-x" type="button" data-sheet-close aria-label="{e(t["close"])}">{icon("x", 20)}</button></div>
<div class="sh-opts" data-sheet-opts>
<a class="sh-opt" href="tel:{SITE["phone"]}" data-direct><span class="sh-ic sh-ic-dark">{icon("phone", 20, 1.75)}</span><span><b>{e(t["sh_call"])}</b><small class="mono">{SITE["phone_display"]}</small></span>{icon("arrow", 16, cls="sh-go")}</a>
<a class="sh-opt" href="{SITE["whatsapp"]}" rel="noopener" target="_blank"><span class="sh-ic sh-ic-wa">{icon("chat", 20, 1.75)}</span><span><b>{e(t["sh_wa"])}</b><small>{e(t["sh_wa_sub"])}</small></span>{icon("arrow", 16, cls="sh-go")}</a>
<button class="sh-opt" type="button" data-sheet-req><span class="sh-ic">{icon("callback", 20, 1.75)}</span><span><b>{e(t["sh_req"])}</b><small>{e(t["sh_req_sub"])}</small></span>{icon("arrow", 16, cls="sh-go")}</button>
</div>
<form class="sh-form" data-callback {form_attrs(lang, t["cb_subject"])} hidden>
<label>{e(t["f_name"])}<input type="text" name="name" autocomplete="name" placeholder="{e(t["f_name_ph"])}" required></label>
<label>{e(t["f_phone"])}<input type="tel" name="phone" autocomplete="tel" placeholder="+995 5__ __ __ __" required></label>
{HONEYPOT}
<button type="submit" class="btn btn-primary btn-block">{icon("callback")}{e(t["cb_submit"])}</button>
<button type="button" class="btn btn-ghost btn-block" data-sheet-back>{icon("back", 15)}{e(t["cb_back"])}</button>
<p class="cf-status" role="status" aria-live="polite" hidden></p>
<p class="cf-priv">{icon("lock", 13)}{e(t["f_priv"])}</p>
</form>
</div>
</dialog>"""


def consult_form(lang, fid="consult", selected=None, heading="h2"):
    t = T[lang]
    opts = "".join(
        f'<option value="{e(s[lang]["name"])}"{" selected" if s["slug"] == selected else ""}>{e(s[lang]["name"])}</option>'
        for s in SERVICES) + f'<option value="{e(t["f_other"])}">{e(t["f_other"])}</option>'
    return f"""<form class="card-form" id="{fid}" data-consult {form_attrs(lang, t["f_subject"])}>
<div class="cf-head"><{heading} class="cf-title">{e(t["form_title"])}</{heading}><p>{e(t["form_sub"])}</p></div>
<div class="cf-body">
<div class="row2">
<label>{e(t["f_name"])}<input type="text" name="name" autocomplete="name" placeholder="{e(t["f_name_ph"])}" required></label>
<label>{e(t["f_phone"])}<input type="tel" name="phone" autocomplete="tel" placeholder="+995 5__ __ __ __" required></label>
</div>
<label>{e(t["f_area"])}<select name="area">{opts}</select></label>
<label>{e(t["f_msg"])}<textarea name="message" rows="4" placeholder="{e(t["f_msg_ph"])}"></textarea></label>
{HONEYPOT}
</div>
<div class="cf-foot">
<button type="submit" class="btn btn-primary btn-block">{e(t["f_submit"])}</button>
<a class="wa-link" href="{SITE["whatsapp"]}" data-wa-link rel="noopener" target="_blank">{icon("chat", 14)}{e(t["f_wa"])}</a>
<p class="cf-status" role="status" aria-live="polite" hidden></p>
<p class="cf-priv">{icon("lock", 13)}{e(t["f_priv"])}</p>
</div>
</form>"""


def eyebrow_h2(eyebrow, h2, raw=False, extra="", hid=None):
    i = f' id="{hid}"' if hid else ""
    return (f'<div class="sec-head"><div class="sec-title"><span class="eyebrow">{e(eyebrow)}</span>'
            f'<h2 class="h2"{i}>{h2 if raw else e(h2)}</h2></div>{extra}</div>')


def svc_card(lang, s, h="h3"):
    d = s[lang]
    return (f'<a class="svc-card" href="{url(lang, "services/" + s["slug"] + "/")}">'
            f'<span class="icon-box">{icon(s["icon"], 20, 1.75)}</span>'
            f'<{h} class="svc-name">{e(d["name"])}</{h}><span class="svc-short">{e(d["short"])}</span>'
            f'<span class="svc-more">{icon("arrow", 15)}</span></a>')


def faq_block(lang, faqs, title=None, eyebrow=None):
    t = T[lang]
    items = "".join(
        f'<details class="faq-item"{" open" if i == 0 else ""}><summary><h3>{e(q)}</h3>{icon("chev", 18)}</summary><div class="faq-a"><p>{e(a)}</p></div></details>'
        for i, (q, a) in enumerate(faqs))
    head_html = eyebrow_h2(eyebrow or t["faq_eyebrow"], title or t["faq_h2"])
    return f'{head_html}<div class="faq">{items}</div>'


def post_card(lang, p):
    d = p[lang]
    s = svc(p["cat"])
    if p["image"]:
        media = f'<img src="{p["image"]}" alt="" loading="lazy" width="600" height="338">'
    else:
        media = f'<span class="pc-art">{icon(s["icon"], 40, 1.25)}</span>'
    return (f'<a class="post-card" href="{url(lang, "blog/" + p["slug"] + "/")}"><div class="pc-media">{media}</div>'
            f'<div class="pc-body"><span class="tag">{e(s[lang]["name"])}</span>'
            f'<h3 class="pc-title">{e(d["title"])}</h3>'
            f'<span class="pc-meta mono"><time datetime="{p["date"]}">{fmt_date(p["date"], lang)}</time> · {p["minutes"]} {e(T[lang]["min_read"])}</span></div></a>')


def contact_list(lang):
    t = T[lang]
    rows = [
        ("phone", t["l_phone"], f'<a class="mono" href="tel:{SITE["phone"]}">{SITE["phone_display"]}</a>'),
        ("chat", t["l_whatsapp"], f'<a href="{SITE["whatsapp"]}" rel="noopener" target="_blank">{SITE["phone_display"]}</a>'),
        ("mail", t["l_email"], f'<a href="mailto:{SITE["email"]}">{SITE["email"]}</a>'),
        ("pin", t["l_office"], e(t["city"])),
        ("clock", t["l_hours"], e(t["hours_long"])),
    ]
    return '<ul class="contact-list">' + "".join(
        f'<li><span class="ci">{icon(ic, 18, 1.75)}</span><span><span class="cl">{e(lbl)}</span><span class="cv">{val}</span></span></li>'
        for ic, lbl, val in rows) + "</ul>"


def cta_section(lang):
    t = T[lang]
    return f"""<section class="sec" id="contact" aria-labelledby="cta-h"><div class="wrap">
<div class="cta-box">
<div class="cta-l">
<h2 class="h2" id="cta-h">{e(t["cta_h2"])}</h2>
<p class="lead-sm">{e(t["cta_p"])}</p>
<div class="btns"><a class="btn btn-primary btn-lg" href="tel:{SITE["phone"]}">{icon("phone")}{e(t["call"])}</a>
<a class="btn btn-outline btn-lg" href="{url(lang, "contact/")}">{e(t["send"])}</a></div>
</div>
<div class="cta-r">{contact_list(lang)}</div>
</div></div></section>"""


def breadcrumb(lang, trail):
    t = T[lang]
    parts = []
    for i, (name, p) in enumerate(trail):
        if i == len(trail) - 1:
            parts.append(f'<li aria-current="page">{e(name)}</li>')
        else:
            parts.append(f'<li><a href="{url(lang, p)}">{e(name)}</a></li>')
    return f'<nav class="crumbs" aria-label="{e(t["breadcrumb"])}"><ol>{"".join(parts)}</ol></nav>'


def page_hero(lang, trail, h1, lead=None, eyebrow=None, extra=""):
    ey = f'<span class="eyebrow">{e(eyebrow)}</span>' if eyebrow else ""
    ld = f'<p class="lead">{e(lead)}</p>' if lead else ""
    return (f'<section class="page-hero grid-bg"><div class="wrap">{breadcrumb(lang, trail)}'
            f'<div class="ph-in">{ey}<h1 class="h1-page">{e(h1)}</h1>{ld}{extra}</div></div></section>')


def aside_card(lang, selected=None):
    t = T[lang]
    return f"""<aside class="side"><div class="side-card">
<h2 class="side-t">{e(t["aside_title"])}</h2><p>{e(t["aside_p"])}</p>
<a class="btn btn-primary btn-block" href="tel:{SITE["phone"]}">{icon("phone")}{SITE["phone_display"]}</a>
<a class="btn btn-outline btn-block" href="{SITE["whatsapp"]}" rel="noopener" target="_blank">{icon("chat")}WhatsApp</a>
<a class="btn btn-ghost btn-block" href="#consult">{e(t["request"])}{icon("arrow", 15)}</a>
<p class="cf-priv">{icon("lock", 13)}{e(t["f_priv"])}</p>
</div></aside>"""


def principles_grid(lang, dark=True):
    return '<div class="princ' + (" princ-dark" if dark else "") + '">' + "".join(
        f'<div class="pr"><span class="mono pr-n">0{i + 1}</span><h3>{e(a)}</h3><p>{e(b)}</p></div>'
        for i, (a, b) in enumerate(T[lang]["principles"])) + "</div>"


def stats(lang):
    t = T[lang]
    data = [("10+", t["s1"]), (str(len(SERVICES)), t["s2"]), ("3", t["s3"]), (t["s4v"], t["s4"])]
    return (f'<section class="stats" aria-label="{e(t["stats_label"])}"><div class="wrap stats-in">' + "".join(
        f'<div class="stat"><span class="stat-v">{e(v)}</span><span class="stat-l">{e(l)}</span></div>' for v, l in data)
        + "</div></section>")


def process(lang):
    t = T[lang]
    steps = "".join(f'<li><span class="step-n">{i + 1}</span><h3>{e(a)}</h3><p>{e(b)}</p></li>'
                    for i, (a, b) in enumerate(t["process"]))
    return (f'<section class="sec bb"><div class="wrap stack">{eyebrow_h2(t["proc_eyebrow"], t["proc_h2"])}'
            f'<ol class="steps">{steps}</ol></div></section>')


# ------------------------------------------------------------------ pages
def build_home(lang):
    t = T[lang]
    title, desc = PAGES["home"][lang]
    checks = "".join(f'<li>{icon("check", 16, 2.25, "acc")}{e(t[k])}</li>' for k in ("check1", "check2", "check3"))
    hero = f"""<section class="hero grid-bg" id="top"><div class="wrap hero-in">
<div class="hero-l">
<span class="pill"><span class="pill-tag">{e(t["badge"])}</span>{e(t["badge_text"])}</span>
<h1 class="h1"><span class="h1-kicker">{e(t["hero_kicker"])}</span>{t["hero_h1"]}</h1>
<p class="lead">{e(t["hero_p"])}</p>
<div class="btns"><a class="btn btn-primary btn-lg" href="#consult">{e(t["btn_book"])}{icon("arrow")}</a>
<a class="btn btn-outline btn-lg" href="#services">{e(t["btn_practice"])}</a></div>
<ul class="checks">{checks}</ul>
</div>
{consult_form(lang)}
</div></section>"""
    services = (f'<section class="sec" id="services"><div class="wrap stack">'
                + eyebrow_h2(t["svc_eyebrow"], t["svc_h2"], extra=f'<a class="btn btn-outline" href="{url(lang, "services/")}">{e(t["svc_all"])}{icon("arrow")}</a>')
                + '<div class="svc-grid">' + "".join(svc_card(lang, s) for s in SERVICES) + "</div></div></section>")
    about = f"""<section class="dark" id="about"><div class="wrap about-in">
<div class="about-l"><span class="eyebrow eyebrow-dim">{e(t["about_eyebrow"])}</span>
<h2 class="h2">{t["about_h2"]}</h2><p class="lead-dark">{e(t["about_p"])}</p>
<a class="btn btn-light" href="{url(lang, "about/")}">{e(t["about_more"])}{icon("arrow")}</a></div>
{principles_grid(lang)}
</div></section>"""
    faq = f'<section class="sec bb"><div class="wrap stack narrow">{faq_block(lang, HOME_FAQ[lang])}</div></section>'
    posts = sorted(POSTS, key=lambda p: p["date"], reverse=True)[:3]
    blog = (f'<section class="sec soft bb" id="blog"><div class="wrap stack">'
            + eyebrow_h2(t["blog_eyebrow"], t["blog_h2"], extra=f'<a class="btn btn-outline bg-white" href="{url(lang, "blog/")}">{e(t["blog_all"])}</a>')
            + '<div class="post-grid">' + "".join(post_card(lang, p) for p in posts) + "</div></div></section>")
    main = hero + stats(lang) + services + foreign_section(lang) + about + process(lang) + faq + blog + cta_section(lang)
    ld = [firm_ld(lang), website_ld(), webpage_ld(lang, "", title, desc), faq_ld(lang, "", HOME_FAQ[lang])]
    return page(lang, "", title, desc, main, "home", ld)


def build_about(lang):
    t = T[lang]
    a = ABOUT[lang]
    title, desc = PAGES["about"][lang]
    trail = [(t["nav_home"], ""), (t["nav_about"], "about/")]
    body = "".join(f"<p>{e(p)}</p>" for p in a["body"])
    values = "".join(f'<div class="val"><span class="mono pr-n acc-t">0{i + 1}</span><h3>{e(x)}</h3><p>{e(y)}</p></div>'
                     for i, (x, y) in enumerate(a["values"]))
    main = (page_hero(lang, trail, a["h1"], a["lead"], t["about_eyebrow"])
            + f'<section class="sec bb"><div class="wrap two-col"><div class="prose">{body}</div>'
            + f'<div class="side-card"><h2 class="side-t">{e(t["aside_title"])}</h2><p>{e(t["aside_p"])}</p>'
            + f'<a class="btn btn-primary btn-block" href="{url(lang, "contact/")}">{e(t["cta"])}</a></div></div></section>'
            + stats(lang)
            + f'<section class="sec"><div class="wrap stack">{eyebrow_h2(t["about_eyebrow"], t["values_h2"])}<div class="vals">{values}</div></div></section>'
            + f'<section class="dark"><div class="wrap stack sec-pad">{eyebrow_h2(t["proc_eyebrow"], t["principles_h2"])}{principles_grid(lang)}</div></section>'
            + process(lang) + cta_section(lang))
    ld = [firm_ld(lang), website_ld(), webpage_ld(lang, "about/", title, desc, "AboutPage", trail), crumbs_ld(lang, trail)]
    return page(lang, "about/", title, desc, main, "about", ld)


def topic_card(lang, x, h="h3"):
    d = x[lang]
    return (f'<a class="svc-card" href="{url(lang, "foreigners/" + x["slug"] + "/")}">'
            f'<span class="icon-box">{icon(x["icon"], 20, 1.75)}</span>'
            f'<{h} class="svc-name">{e(d["name"])}</{h}><span class="svc-short">{e(d["short"])}</span>'
            f'<span class="svc-more">{icon("arrow", 15)}</span></a>')


def foreign_section(lang):
    f = FOREIGN_UI[lang]
    return (f'<section class="sec soft bb" id="foreigners"><div class="wrap stack">'
            + eyebrow_h2(f["eyebrow"], f["h2"], extra=f'<a class="btn btn-outline bg-white" href="{url(lang, "foreigners/")}">{e(f["more"])}{icon("arrow")}</a>')
            + f'<p class="lead">{e(FOREIGN_HUB[lang]["lead"])}</p>'
            + '<div class="svc-grid">' + "".join(topic_card(lang, x) for x in FOREIGN_TOPICS) + "</div></div></section>")


def build_foreigners(lang):
    t, f, h = T[lang], FOREIGN_UI[lang], FOREIGN_HUB[lang]
    path = "foreigners/"
    trail = [(t["nav_home"], ""), (f["nav"], path)]
    points = "".join(f'<div class="val"><span class="mono pr-n acc-t">0{i + 1}</span><h3>{e(a)}</h3><p>{e(b)}</p></div>'
                     for i, (a, b) in enumerate(h["points"]))
    hero_extra = (f'<div class="btns"><a class="btn btn-primary btn-lg" href="#consult">{e(t["request"])}{icon("arrow")}</a>'
                  f'<a class="btn btn-outline btn-lg" href="{SITE["whatsapp"]}" rel="noopener" target="_blank">{icon("chat")}WhatsApp</a></div>')
    main = (page_hero(lang, trail, h["h1"], h["lead"], f["eyebrow"], hero_extra)
            + f'<section class="sec bb"><div class="wrap stack">{eyebrow_h2(f["eyebrow"], f["topics"])}'
            + '<div class="svc-grid">' + "".join(topic_card(lang, x, "h2") for x in FOREIGN_TOPICS) + "</div>"
            + f'<div class="vals">{points}</div></div></section>'
            + f'<section class="sec bb"><div class="wrap stack narrow">{faq_block(lang, h["faq"])}</div></section>'
            + f'<section class="sec soft bb"><div class="wrap form-wrap">{consult_form(lang)}</div></section>'
            + cta_section(lang))
    item_list = {"@type": "ItemList", "itemListElement": [
        {"@type": "ListItem", "position": i + 1, "url": abs_url(lang, f"foreigners/{x['slug']}/"), "name": x[lang]["name"]}
        for i, x in enumerate(FOREIGN_TOPICS)]}
    ld = [firm_ld(lang), website_ld(), webpage_ld(lang, path, h["title"], h["desc"], "CollectionPage", trail),
          crumbs_ld(lang, trail), item_list, faq_ld(lang, path, h["faq"])]
    return page(lang, path, h["title"], h["desc"], main, "foreigners", ld)


def build_topic(lang, x):
    t, f = T[lang], FOREIGN_UI[lang]
    d = x[lang]
    path = f"foreigners/{x['slug']}/"
    title = with_brand(d["title"])
    desc = f'{d["short"]} {t["desc_tail"]}'
    trail = [(t["nav_home"], ""), (f["nav"], "foreigners/"), (d["name"], path)]
    items = "".join(f"<li>{icon('check', 16, 2.25, 'acc')}<span>{e(i)}</span></li>" for i in d["items"])
    body = "".join(f"<p>{e(p)}</p>" for p in d["body"])
    rel = svc(x["service"])
    hero_extra = (f'<div class="btns"><a class="btn btn-primary btn-lg" href="#consult">{e(t["request"])}{icon("arrow")}</a>'
                  f'<a class="btn btn-outline btn-lg mono" href="tel:{SITE["phone"]}">{icon("phone")}{SITE["phone_display"]}</a></div>')
    others = [o for o in FOREIGN_TOPICS if o["slug"] != x["slug"]]
    main = (page_hero(lang, trail, d["title"], d["lead"], f["eyebrow"], hero_extra)
            + f'<section class="sec bb"><div class="wrap two-col"><div class="stack-md">'
            + f'<div class="prose">{body}</div>'
            + f'<div><h2 class="h3">{e(t["what_we_handle"])}</h2><ul class="checklist">{items}</ul></div>'
            + f'<div class="stack-sm">{faq_block(lang, d["faq"], t["svc_faq"], d["name"])}</div>'
            + f'<p><span class="muted">{e(f["related"])}: </span><a class="link-arrow" href="{url(lang, "services/" + rel["slug"] + "/")}">{e(rel[lang]["name"])}{icon("arrow", 15)}</a></p>'
            + f'</div>{aside_card(lang)}</div></section>'
            + f'<section class="sec soft bb"><div class="wrap form-wrap">{consult_form(lang, "consult", x["service"])}</div></section>'
            + f'<section class="sec"><div class="wrap stack">{eyebrow_h2(f["eyebrow"], f["topics"])}'
            + '<div class="svc-grid">' + "".join(topic_card(lang, o) for o in others) + "</div></div></section>")
    service_ld = {
        "@type": "Service", "@id": abs_url(lang, path) + "#service", "name": d["title"], "serviceType": d["name"],
        "description": d["lead"], "url": abs_url(lang, path),
        "provider": {"@id": D + "/#firm"}, "areaServed": {"@type": "Country", "name": "Georgia"},
        "audience": {"@type": "Audience", "audienceType": "Foreign nationals in Georgia"},
    }
    ld = [firm_ld(lang), website_ld(), webpage_ld(lang, path, title, desc, "WebPage", trail), crumbs_ld(lang, trail),
          service_ld, faq_ld(lang, path, d["faq"])]
    return page(lang, path, title, desc, main, "foreigners", ld)


def build_services(lang):
    t = T[lang]
    title, desc = PAGES["services"][lang]
    trail = [(t["nav_home"], ""), (t["nav_services"], "services/")]
    rows = "".join(
        f'<article class="svc-row"><span class="icon-box">{icon(s["icon"], 20, 1.75)}</span><div>'
        f'<h2><a href="{url(lang, "services/" + s["slug"] + "/")}">{e(s[lang]["name"])}</a></h2>'
        f'<p class="svc-lead">{e(s[lang]["short"])}</p><p>{e(s[lang]["body"][0])}</p>'
        f'<a class="link-arrow" href="{url(lang, "services/" + s["slug"] + "/")}">{e(t["read_more"])}{icon("arrow", 15)}</a></div></article>'
        for s in SERVICES)
    main = (page_hero(lang, trail, t["svc_h2"], desc, t["svc_eyebrow"])
            + f'<section class="sec"><div class="wrap"><div class="svc-rows">{rows}</div></div></section>'
            + process(lang) + cta_section(lang))
    item_list = {"@type": "ItemList", "itemListElement": [
        {"@type": "ListItem", "position": i + 1, "url": abs_url(lang, f"services/{s['slug']}/"), "name": s[lang]["name"]}
        for i, s in enumerate(SERVICES)]}
    ld = [firm_ld(lang), website_ld(), webpage_ld(lang, "services/", title, desc, "CollectionPage", trail), crumbs_ld(lang, trail), item_list]
    return page(lang, "services/", title, desc, main, "services", ld)


def related_posts(lang, slug):
    posts = [p for p in POSTS if p["cat"] == slug]
    if not posts:
        return ""
    t = T[lang]
    return (f'<section class="sec bb"><div class="wrap stack">{eyebrow_h2(t["blog_eyebrow"], t["blog_h2"])}'
            + '<div class="post-grid">' + "".join(post_card(lang, p) for p in posts) + "</div></div></section>")


def build_service(lang, s):
    t = T[lang]
    d = s[lang]
    path = f"services/{s['slug']}/"
    title = with_brand(d["title"])
    desc = d.get("meta") or f'{d["short"]} {t["desc_tail"]}'
    trail = [(t["nav_home"], ""), (t["nav_services"], "services/"), (d["name"], path)]
    items = "".join(f"<li>{icon('check', 16, 2.25, 'acc')}<span>{e(x)}</span></li>" for x in d["items"])
    body = "".join(f"<p>{e(p)}</p>" for p in d["body"])
    others = [o for o in SERVICES if o["slug"] != s["slug"]]
    hero_extra = (f'<div class="btns"><a class="btn btn-primary btn-lg" href="#consult">{e(t["request"])}{icon("arrow")}</a>'
                  f'<a class="btn btn-outline btn-lg mono" href="tel:{SITE["phone"]}">{icon("phone")}{SITE["phone_display"]}</a></div>')
    main = (page_hero(lang, trail, d["title"], d["lead"], d["name"], hero_extra)
            + f'<section class="sec bb"><div class="wrap two-col"><div class="stack-md">'
            + f'<div class="prose">{body}</div>'
            + f'<div><h2 class="h3">{e(t["what_we_handle"])}</h2><ul class="checklist">{items}</ul></div>'
            + f'<div class="stack-sm">{faq_block(lang, d["faq"], t["svc_faq"], d["name"])}</div>'
            + f'</div>{aside_card(lang, s["slug"])}</div></section>'
            + f'<section class="sec soft bb"><div class="wrap form-wrap">{consult_form(lang, "consult", s["slug"])}</div></section>'
            + related_posts(lang, s["slug"])
            + f'<section class="sec"><div class="wrap stack">{eyebrow_h2(t["svc_eyebrow"], t["other_areas"])}'
            + '<div class="svc-grid">' + "".join(svc_card(lang, o) for o in others) + "</div></div></section>")
    service_ld = {
        "@type": "Service", "@id": abs_url(lang, path) + "#service", "name": d["name"], "serviceType": d["name"],
        "description": d["lead"], "url": abs_url(lang, path),
        "provider": {"@id": D + "/#firm"}, "areaServed": {"@type": "Country", "name": "Georgia"},
        "audience": {"@type": "Audience", "audienceType": "Individuals and businesses"},
    }
    ld = [firm_ld(lang), website_ld(), webpage_ld(lang, path, title, desc, "WebPage", trail), crumbs_ld(lang, trail),
          service_ld, faq_ld(lang, path, d["faq"])]
    return page(lang, path, title, desc, main, "services", ld)


def build_blog(lang):
    t = T[lang]
    title, desc = PAGES["blog"][lang]
    trail = [(t["nav_home"], ""), (t["nav_blog"], "blog/")]
    posts = sorted(POSTS, key=lambda p: p["date"], reverse=True)
    main = (page_hero(lang, trail, t["blog_h2"], desc, t["blog_eyebrow"])
            + '<section class="sec soft bb"><div class="wrap"><div class="post-grid">'
            + "".join(post_card(lang, p) for p in posts) + "</div></div></section>" + cta_section(lang))
    blog_ld = {"@type": "Blog", "@id": abs_url(lang, "blog/") + "#blog", "name": t["blog_h2"], "inLanguage": lang,
               "publisher": {"@id": D + "/#firm"},
               "blogPost": [{"@type": "BlogPosting", "headline": p[lang]["title"], "url": abs_url(lang, f"blog/{p['slug']}/"),
                             "datePublished": p["date"]} for p in posts]}
    ld = [firm_ld(lang), website_ld(), webpage_ld(lang, "blog/", title, desc, "CollectionPage", trail), crumbs_ld(lang, trail), blog_ld]
    return page(lang, "blog/", title, desc, main, "blog", ld)


def render_blocks(blocks):
    out = []
    for kind, val in blocks:
        if kind == "p":
            out.append(f"<p>{e(val)}</p>")
        elif kind == "h2":
            out.append(f"<h2>{e(val)}</h2>")
        else:
            out.append(f"<{kind}>" + "".join(f"<li>{e(x)}</li>" for x in val) + f"</{kind}>")
    return "".join(out)


def build_post(lang, p):
    t = T[lang]
    d = p[lang]
    path = f"blog/{p['slug']}/"
    title = with_brand(d["title"])
    trail = [(t["nav_home"], ""), (t["nav_blog"], "blog/"), (d["title"], path)]
    s = svc(p["cat"])
    meta = (f'<p class="post-meta mono"><span class="tag">{e(s[lang]["name"])}</span>'
            f'<time datetime="{p["date"]}">{fmt_date(p["date"], lang)}</time> · {p["minutes"]} {e(t["min_read"])}</p>')
    img = f'<img class="post-img" src="{p["image"]}" alt="{e(d["title"])}" width="900" height="900">' if p["image"] else ""
    others = [o for o in POSTS if o["slug"] != p["slug"]][:2]
    main = (page_hero(lang, trail, d["title"], d["desc"], None, meta)
            + f'<section class="sec bb"><div class="wrap two-col"><article class="prose article">{img}{render_blocks(d["body"])}'
            + f'<p class="note">{icon("alert", 16)}<span>{e(t["article_note"])}</span></p>'
            + f'<p><a class="link-arrow" href="{url(lang, "services/" + s["slug"] + "/")}">{e(s[lang]["name"])}{icon("arrow", 15)}</a></p>'
            + f'</article>{aside_card(lang)}</div></section>'
            + f'<section class="sec soft bb"><div class="wrap form-wrap">{consult_form(lang, "consult", s["slug"])}</div></section>'
            + (f'<section class="sec"><div class="wrap stack">{eyebrow_h2(t["blog_eyebrow"], t["back_blog"], extra=f"<a class=\"btn btn-outline\" href=\"{url(lang, "blog/")}\">{e(t["blog_all"])}</a>")}'
               + '<div class="post-grid">' + "".join(post_card(lang, o) for o in others) + "</div></div></section>" if others else ""))
    image = p["image"] or f"/assets/og-{lang}.png"
    art = {
        "@type": "BlogPosting", "@id": abs_url(lang, path) + "#article", "headline": d["title"], "description": d["desc"],
        "inLanguage": lang, "datePublished": p["date"], "dateModified": max(p["date"], SITE["updated"]),
        "image": {"@type": "ImageObject", "url": D + image, "width": IMAGE_SIZES.get(image, (1200, 630))[0],
                  "height": IMAGE_SIZES.get(image, (1200, 630))[1]},
        "author": {"@type": "Organization", "@id": D + "/#firm", "name": SITE["legal_name"], "url": D + "/"},
        "publisher": {"@type": "Organization", "@id": D + "/#firm", "name": SITE["legal_name"],
                      "logo": {"@type": "ImageObject", "url": D + "/icon-512.png"}},
        "wordCount": sum(len((v if isinstance(v, str) else " ".join(v)).split()) for _, v in d["body"]),
        "mainEntityOfPage": {"@id": abs_url(lang, path) + "#webpage"}, "about": {"@type": "Thing", "name": s[lang]["name"]},
    }
    ld = [firm_ld(lang), website_ld(), webpage_ld(lang, path, title, d["desc"], "WebPage", trail), crumbs_ld(lang, trail), art]
    extra = (f'\n<meta property="article:published_time" content="{p["date"]}">'
             f'\n<meta property="article:modified_time" content="{max(p["date"], SITE["updated"])}">'
             f'\n<meta property="article:section" content="{e(s[lang]["name"])}">')
    return page(lang, path, title, d["desc"], main, "blog", ld, "article", image, extra=extra)


def build_contact(lang):
    t = T[lang]
    title, desc = PAGES["contact"][lang]
    trail = [(t["nav_home"], ""), (t["nav_contact"], "contact/")]
    main = (page_hero(lang, trail, t["contact_h1"], t["contact_lead"])
            + f'<section class="sec"><div class="wrap contact-grid"><div class="stack-md">{contact_list(lang)}'
            + f'<div class="urgent"><span class="ci ci-acc">{icon("alert", 18, 1.75)}</span><div><h2>{e(t["urgent_t"])}</h2><p>{e(t["urgent_p"])}</p>'
            + f'<a class="btn btn-primary" href="tel:{SITE["phone"]}">{icon("phone")}{e(t["call"])}</a></div></div>'
            + f'</div>{consult_form(lang)}</div></section>')
    ld = [firm_ld(lang), website_ld(), webpage_ld(lang, "contact/", title, desc, "ContactPage", trail), crumbs_ld(lang, trail)]
    return page(lang, "contact/", title, desc, main, "contact", ld)


def build_privacy(lang):
    t = T[lang]
    title, desc = PAGES["privacy"][lang]
    trail = [(t["nav_home"], ""), (t["privacy"], "privacy/")]
    body = "".join(f"<h2>{e(h)}</h2><p>{e(p)}</p>" for h, p in PRIVACY[lang])
    main = (page_hero(lang, trail, t["privacy"], desc)
            + f'<section class="sec"><div class="wrap"><div class="prose narrow-prose">{body}'
            + f'<p class="muted">{e(t["updated_lbl"])}: <time datetime="{SITE["updated"]}">{fmt_date(SITE["updated"], lang)}</time></p></div></div></section>')
    ld = [firm_ld(lang), website_ld(), webpage_ld(lang, "privacy/", title, desc, "WebPage", trail), crumbs_ld(lang, trail)]
    return page(lang, "privacy/", title, desc, main, None, ld)


def build_404(lang):
    t = T[lang]
    popular = [("shield", "services/criminal-defense/", svc("criminal-defense")[lang]["name"]),
               ("users", "services/family-law/", svc("family-law")[lang]["name"]),
               ("briefcase", "services/", t["nav_services"]),
               ("globe", "foreigners/", FOREIGN_UI[lang]["nav"]),
               ("building", "about/", t["nav_about"]),
               ("mail", "contact/", t["nav_contact"])]
    grid = "".join(f'<a href="{url(lang, p)}">{icon(ic, 16, 1.75)}{e(n)}</a>' for ic, p, n in popular)
    main = (f'<section class="grid-bg bb"><div class="wrap"><div class="nf-wrap">'
            f'<span class="nf-code" aria-hidden="true">404</span>'
            f'<h1 class="h1-page">{e(t["nf_title"])}</h1>'
            f'<p class="lead">{e(t["nf_p"])} {e(t["nf_p2"])}</p>'
            f'<div class="btns"><a class="btn btn-primary btn-lg" href="{url(lang)}">{icon("back", 16)}{e(t["nf_home"])}</a>'
            f'<a class="btn btn-outline btn-lg" href="tel:{SITE["phone"]}">{icon("phone")}{SITE["phone_display"]}</a></div>'
            f'<span class="nf-links-h">{e(t["nf_popular"])}</span><div class="nf-grid">{grid}</div>'
            f'</div></div></section>')
    html_ = page(lang, "", t["nf_title"] + " | MMLAW", t["nf_p"], main, None, [], noindex=True)
    # not a real page: no canonical / language alternates
    html_ = "\n".join(l for l in html_.split("\n") if 'rel="canonical"' not in l and '<link rel="alternate" hreflang=' not in l)
    if lang == DEFAULT_LANG:
        # GitHub Pages serves one 404.html for every missing address: show the English or
        # Russian version for /en/... and /ru/... addresses, keeping the address bar as is.
        swap = ('<script>(function(){var m=location.pathname.match(/^\\/(en|ru)\\//);if(!m)return;'
                'var d=document.documentElement;d.style.visibility="hidden";'
                'fetch("/"+m[1]+"/404/").then(function(r){return r.text()}).then(function(h){document.open();document.write(h);document.close()})'
                '.catch(function(){d.style.visibility=""})})()</script>')
        html_ = html_.replace('<meta charset="utf-8">', '<meta charset="utf-8">\n' + swap, 1)
    return html_


def redirect_stub(target):
    return (f'<!doctype html><html lang="ka"><head><meta charset="utf-8"><title>MMLAW</title>'
            f'<meta name="robots" content="noindex"><link rel="canonical" href="{D}{target}">'
            f'<meta http-equiv="refresh" content="0; url={target}">'
            f'<script>location.replace("{target}"+location.search+location.hash)</script></head>'
            f'<body><a href="{target}">{D}{target}</a></body></html>\n{GENERATED_MARK}\n')


# ------------------------------------------------------------------ write
def write(rel, content):
    full = os.path.join(ROOT, rel)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with open(full, "w", encoding="utf-8") as f:
        f.write(content)


def all_paths():
    paths = ["", "about/", "services/", "blog/", "contact/", "privacy/"]
    paths += [f"services/{s['slug']}/" for s in SERVICES]
    paths += [f"blog/{p['slug']}/" for p in POSTS]
    paths += ["foreigners/"] + [f"foreigners/{x['slug']}/" for x in FOREIGN_TOPICS]
    return paths


def priority(path):
    if path == "":
        return "1.0"
    if path.startswith(("services", "foreigners")):
        return "0.9"
    if path in ("about/", "contact/"):
        return "0.8"
    if path == "privacy/":
        return "0.3"
    return "0.7"


def sitemap():
    urls = []
    for path in all_paths():
        lastmod = SITE["updated"]
        for p in POSTS:
            if path == f"blog/{p['slug']}/":
                lastmod = max(p["date"], SITE["updated"])
        alts = "".join(f'<xhtml:link rel="alternate" hreflang="{l}" href="{abs_url(l, path)}"/>' for l in LANGS)
        alts += f'<xhtml:link rel="alternate" hreflang="x-default" href="{abs_url(DEFAULT_LANG, path)}"/>'
        for l in LANGS:
            urls.append(f"<url><loc>{abs_url(l, path)}</loc>{alts}<lastmod>{lastmod}</lastmod><priority>{priority(path)}</priority></url>")
    return ('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" '
            'xmlns:xhtml="http://www.w3.org/1999/xhtml">\n' + "\n".join(urls) + "\n</urlset>\n")


def robots():
    return f"""User-agent: *
Allow: /

# AI assistants and answer engines are welcome to read and cite this site.
User-agent: GPTBot
Allow: /
User-agent: OAI-SearchBot
Allow: /
User-agent: ChatGPT-User
Allow: /
User-agent: ClaudeBot
Allow: /
User-agent: Claude-User
Allow: /
User-agent: Claude-SearchBot
Allow: /
User-agent: PerplexityBot
Allow: /
User-agent: Google-Extended
Allow: /
User-agent: Applebot-Extended
Allow: /

Sitemap: {D}/sitemap.xml
"""


def llms_txt():
    t = T["en"]
    lines = [
        "# MMLAW Law Firm (mmlaw.ge)", "",
        "> MMLAW is a law firm in Tbilisi, Georgia, with more than 10 years of legal practice. It represents individuals and "
        "companies in criminal, civil, administrative, labour, corporate, real estate, family, intellectual property and "
        "juvenile justice matters, before courts of all instances in Georgia. Consultations in Georgian, English and Russian; "
        "the first consultation is free. Formerly at lfs.ge.", "",
        f"- Phone / WhatsApp: {SITE['phone_display']}",
        f"- Email: {SITE['email']}",
        f"- Office: Tbilisi, Georgia. Hours: {t['hours_long']}",
        "- Languages: Georgian (default, https://mmlaw.ge/ka/), English (https://mmlaw.ge/en/), Russian (https://mmlaw.ge/ru/)", "",
        "## Practice areas", "",
    ]
    lines += [f"- [{s['en']['name']}]({abs_url('en', 'services/' + s['slug'] + '/')}): {s['en']['lead']}" for s in SERVICES]
    lines += ["", "## For foreigners in Georgia", "", f"- [Legal help for foreigners]({abs_url('en', 'foreigners/')}): {FOREIGN_HUB['en']['lead']}"]
    lines += [f"- [{x['en']['title']}]({abs_url('en', 'foreigners/' + x['slug'] + '/')}): {x['en']['lead']}" for x in FOREIGN_TOPICS]
    lines += ["", "## Key pages", "",
              f"- [About the firm]({abs_url('en', 'about/')})",
              f"- [Contact]({abs_url('en', 'contact/')})",
              f"- [Frequently asked questions]({abs_url('en')}#faq)", "", "## Articles", ""]
    lines += [f"- [{p['en']['title']}]({abs_url('en', 'blog/' + p['slug'] + '/')}): {p['en']['desc']}" for p in POSTS]
    lines += ["", "## Optional", "", f"- [Full text of the site in English]({D}/llms-full.txt)", f"- [Sitemap]({D}/sitemap.xml)", ""]
    return "\n".join(lines)


def llms_full():
    """Complete English content in one plain-text file for AI assistants."""
    en = "en"
    t = T[en]
    out = [llms_txt().split("## Practice areas")[0].rstrip(), "", "## About the firm", ""]
    out += ABOUT[en]["body"] + [""]
    out += [f"- {a}: {b}" for a, b in ABOUT[en]["values"]] + [""]
    out += ["## How we work", ""] + [f"{i + 1}. {a} — {b}" for i, (a, b) in enumerate(t["process"])] + [""]
    out += ["## Frequently asked questions", ""]
    for q, a in HOME_FAQ[en]:
        out += [f"### {q}", a, ""]
    for sv in SERVICES:
        d = sv[en]
        out += [f"## {d['title']}", f"URL: {abs_url(en, 'services/' + sv['slug'] + '/')}", "", d["lead"], ""]
        out += d["body"] + [""] + [f"{t['what_we_handle']}:"] + [f"- {x}" for x in d["items"]] + [""]
        for q, a in d["faq"]:
            out += [f"### {q}", a, ""]
    out += [f"## {FOREIGN_HUB[en]['h1']}", f"URL: {abs_url(en, 'foreigners/')}", "", FOREIGN_HUB[en]["lead"], ""]
    for q, a in FOREIGN_HUB[en]["faq"]:
        out += [f"### {q}", a, ""]
    for x in FOREIGN_TOPICS:
        d = x[en]
        out += [f"## {d['title']}", f"URL: {abs_url(en, 'foreigners/' + x['slug'] + '/')}", "", d["lead"], ""]
        out += d["body"] + [""] + [f"- {i}" for i in d["items"]] + [""]
        for q, a in d["faq"]:
            out += [f"### {q}", a, ""]
    for p in sorted(POSTS, key=lambda x: x["date"], reverse=True):
        d = p[en]
        out += [f"## {d['title']}", f"URL: {abs_url(en, 'blog/' + p['slug'] + '/')} — published {p['date']}", ""]
        for kind, val in d["body"]:
            if kind == "h2":
                out += [f"### {val}"]
            elif kind == "p":
                out += [val, ""]
            else:
                out += [f"- {x}" for x in val] + [""]
    out += ["", t["disclaimer"], ""]
    return "\n".join(out)


def clean_generated():
    """Remove previously generated HTML so deleted pages don't linger."""
    for dirpath, dirnames, filenames in os.walk(ROOT):
        dirnames[:] = [d for d in dirnames if not d.startswith(".") and d not in ("tools", "assets", "node_modules")
                       and "Desktop-html" not in d]
        for fn in filenames:
            if fn.endswith(".html"):
                fp = os.path.join(dirpath, fn)
                with open(fp, encoding="utf-8", errors="ignore") as f:
                    if GENERATED_MARK in f.read():
                        os.remove(fp)
        if dirpath != ROOT and not os.listdir(dirpath):
            os.rmdir(dirpath)


def og_images():
    chrome = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
    tag = {"ka": "საადვოკატო ბიურო · თბილისი", "en": "Law Firm · Tbilisi, Georgia", "ru": "Юридическая фирма · Тбилиси"}
    for lang in LANGS:
        t = T[lang]
        doc = f"""<!doctype html><html lang="{lang}"><head><meta charset="utf-8">
<link href="https://fonts.googleapis.com/css2?family=Noto+Sans+Georgian:wght@500;600;700&display=block" rel="stylesheet">
<style>*{{margin:0;box-sizing:border-box}}body{{width:1200px;height:630px;font-family:HelveticaNeue,'Helvetica Neue',Arial,Helvetica,'Noto Sans Georgian',sans-serif;background:#fff;color:#09090b;
background-image:linear-gradient(#f0f0f2 1px,transparent 1px),linear-gradient(90deg,#f0f0f2 1px,transparent 1px);background-size:48px 48px;
display:flex;flex-direction:column;justify-content:space-between;padding:72px 80px}}
.b{{display:flex;gap:18px;align-items:center}}.m{{width:72px;height:72px;border-radius:16px;background:#18181b;color:#fafafa;display:flex;align-items:center;justify-content:center}}
.n{{font-size:44px;font-weight:700;letter-spacing:-.02em;line-height:1}}.s{{font-size:20px;color:#52525b;margin-top:6px}}
h1{{font-size:{76 if lang == "en" else 64}px;line-height:1.05;font-weight:600;letter-spacing:{"-.03em" if lang != "ka" else "-.01em"}}}
.f{{display:flex;justify-content:space-between;align-items:center;font-size:26px;color:#3f3f46}}.d{{color:{SITE["accent"]};font-weight:600}}</style></head>
<body><div class="b"><span class="m">{icon("scale", 40, 1.6)}</span><div><div class="n">MMLAW</div><div class="s">{e(tag[lang])}</div></div></div>
<h1>{t["hero_h1"]}</h1>
<div class="f"><span>{SITE["phone_display"]} · {e(t["badge_text"])}</span><span class="d">mmlaw.ge</span></div></body></html>"""
        with tempfile.NamedTemporaryFile("w", suffix=".html", delete=False, encoding="utf-8") as f:
            f.write(doc)
            src = f.name
        out = os.path.join(ROOT, "assets", f"og-{lang}.png")
        subprocess.run([chrome, "--headless=new", "--disable-gpu", "--hide-scrollbars", "--virtual-time-budget=8000",
                        "--window-size=1200,630", f"--screenshot={out}", "file://" + src],
                       check=True, capture_output=True)
        os.unlink(src)
        print("og image", out)


def main():
    clean_generated()
    for lang in LANGS:
        loc = lambda key: url(lang, key).lstrip("/") + "index.html"
        write(loc(""), build_home(lang))
        write(loc("about/"), build_about(lang))
        write(loc("services/"), build_services(lang))
        for s in SERVICES:
            write(loc(f"services/{s['slug']}/"), build_service(lang, s))
        write(loc("blog/"), build_blog(lang))
        for p in POSTS:
            write(loc(f"blog/{p['slug']}/"), build_post(lang, p))
        write(loc("contact/"), build_contact(lang))
        write(loc("privacy/"), build_privacy(lang))
        write(loc("foreigners/"), build_foreigners(lang))
        for x in FOREIGN_TOPICS:
            write(loc(f"foreigners/{x['slug']}/"), build_topic(lang, x))
    write("404.html", build_404(DEFAULT_LANG))
    for lang in LANGS:
        if lang != DEFAULT_LANG:
            write(f"{lang}/404/index.html", build_404(lang))
    # Forwarding: bare domain + root paths -> Georgian; older English-word addresses
    # (incl. lfs.ge's /ka/... and /ru/... links) -> the localized ones.
    real = {url(l, k) for l in LANGS for k in all_paths()}
    for key in all_paths():
        if key:  # the bare domain itself is the Georgian home page
            write(f"{key}index.html", redirect_stub(url(DEFAULT_LANG, key)))
        for lang in LANGS:
            old = f"/{lang}/{key}"
            if old not in real:
                write(f"{lang}/{key}index.html", redirect_stub(url(lang, key)))
    for old, key in LEGACY.items():
        write(old.lstrip("/") + "index.html", redirect_stub(url(key[0], key[1])))
    # mmlaw.ge/ka/ shows the same Georgian home page (canonical: the bare domain)
    write("ka/index.html", build_home(DEFAULT_LANG))
    write("sitemap.xml", sitemap())
    write("robots.txt", robots())
    write("llms.txt", llms_txt())
    write("llms-full.txt", llms_full())
    if "--og" in sys.argv:
        og_images()
    n = sum(1 for _ in all_paths()) * len(LANGS)
    print(f"built {n} pages + 404, sitemap.xml, robots.txt, llms.txt")


if __name__ == "__main__":
    main()
